### ISSUE TITLE
Import  not working

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/externalimport_tut#4]
The extension is not working.
Even after correction of the filename no imports are done.
I get in devlog the right data shown till Importer.php, line 1353, next log-entry is without data in Importer.php, line 1374 and in ReportingUtility.php, line 86 I only get this shown:

```
array (
  2 => 
  array (
  ),
  1 => 
  array (
  ),
  0 => 
  array (
    0 => '0 new record(s) inserted',
    1 => '0 existing record(s) updated',
    2 => '0 existing record(s) deleted',
  ),
)
```

**Comment by DavidBruchmann** [comment]
I tried several imports with increasing priority but I never got any data at all written in any table.
I tried only the example without news.

**Comment by DavidBruchmann** [comment]
Issue fixed, the page-type must be folder, then it works.

**Comment by fsuter** [comment]
Hmm, it is interesting that this is not reported by DataHandler as an error. Can you check if this generates an entry in the sys_log table? If not I'm afraid there's not much that can be error to inform the user about the problem.

**Comment by DavidBruchmann** [comment]
Sorry, no trace of it in sys_log.
But remarked something else there, will verify it tomorrow and perhaps open another issue then in external_import ;-)
