### ISSUE TITLE
missing requirement typo3/cms-reactions

### ISSUE THREAD

**Issue by Make66** [cobwebch/externalimport_tut#8]
pls add typo3/cms-reactions to the requirements in your composer.json to prevent a:
_Error
Interface "TYPO3\CMS\Reactions\Reaction\ReactionInterface" not found
in /var/www/html/vendor/cobweb/external_import/Classes/Reaction/ImportReaction.php line 34_

**Comment by fsuter** [comment]
This is actually related to external_import, not externalimport_tut, and the issue has already been reported: https://github.com/cobwebch/external_import/issues/298

Unfortunately, there's no simple solution as long as compatibility with TYPO3 11 is preserved. This will be dropped in the next major version, but the release will follow that of TYPO3 13 and hence not happen so soon.

Sorry for the inconvenience.
